### ISSUE TITLE
Multiprocessing not working

### ISSUE THREAD

**Issue by Puneet-Singh1996** [joddiy/multiprocess#1]
import multiprocessing
     from multiprocessing import Pool
     
     class pdf_gen():
       def __init__(self):
         pdf = self.pdf = FPDF()
         pdf.set_auto_page_break(True,0.1)
       
       def get_data_from_mysql(self) :
         pdf = self.pdf
         # connection is established and result is stored in 'res'.
         dup = []
         dup.insert(0,res)
         z = tuple(dup)
         return z

       def mysql_to_pdf_data(self,*result) :
         try : 
           pdf = self.pdf 
           # Entered data need to be in pdf
         finally : 
           pdf.output('save_pdf.pdf','F')

     def main() :
       pdf = pdf_gen()
       recover_data = pdf.get_data_from_mysql()
       pool = multiprocessing.Pool(multiprocessing.cpu_count())
       pool.map(pdf.mysql_to_pdf_data,recover_data)

Below picture is the utilisation of my CPU that depicts it only using single core while having 2 cores.
![capture](https://user-images.githubusercontent.com/37451749/40850121-a34c4332-6578-11e8-96f7-7dccd1ced476.PNG)

**Comment by joddiy** [comment]
I'm very glad you can notice this tiny project.

But I think the **multiprocessing** is the python's official package rather than my project...

I'm sorry I haven't translated the documents into English, so if you have any questions, plz let me know.

**Comment by joddiy** [comment]
And I think you can try this project just like the Usage.

This project is funny, and I have written several crawlers using it.

**Comment by Puneet-Singh1996** [comment]
I am stuck in python multiprocessing and find any help to solve this matter.
